### ISSUE TITLE
Icons not displaying correctly (?)

### ISSUE THREAD

**Issue by pogramos** [Shirk/statustimers#1]
Version: v4.0.902
Ashita Version: Latest (from github)
Hi!
I'm kinda new to using addons and started using ashita this week (or so)... I installed statustimers but some of my icons are being cut in half (kinda), i've already tried unloading all of my addons and loading only ST but it didn't solve. 

should It behave like this or is there something wrong?

![image](https://user-images.githubusercontent.com/15428949/169221919-fe9195d4-9216-45d9-a3a0-c32add9d2155.png)

**Comment by Shirk** [comment]
Never seen that - and no, it's not how it's supposed to behave.
Can you give me a bit more info?

Are you using the default icons or a custom icon set?

Does it happen for all status effects except for the first or only for certain effects regardless of position?

What's your resolution and menu resolution set to?

Do you have Window's HiDPI scaling enabled for FFXI (that breaks all kinds of things and needs to be disabled explicitly)?

What GPU are you using (imgui has some issues on ATI/AMD)?

**Comment by pogramos** [comment]
> **Are you using the default icons or a custom icon set?**

Default icon set

> **Does it happen for all status effects except for the first or only for certain effects regardless of position?**

Yes, regardless of position some of them are being cut... only flee icon won't cut at all.


> **What's your resolution and menu resolution set to?**

Monitor resolution: 1920x1080 (3840 x 2160)

> **Do you have Window's HiDPI scaling enabled for FFXI (that breaks all kinds of things and needs to be disabled explicitly)?**

You mean the configuration under compatibility? 
Both enabled and disabled it remains the same. 

> **What GPU are you using (imgui has some issues on ATI/AMD)?**

RTX 3080

**Comment by pogramos** [comment]
Update:
Apparently reinstalling everything from scratch made it work.

I'll reinstal everything that I was using before, and check after each step if it will break again.

I'll give you a feedback.

![image](https://user-images.githubusercontent.com/15428949/169355383-43953386-f93d-43ae-a8dd-6a7cb81b5e2a.png)
