### ISSUE TITLE
unable to remove buffs with ingame ui

### ISSUE THREAD

**Issue by Chibloom** [Shirk/statustimers#11]
previous versions had this function, so caused when transition to 4.0.911 -> 4.1.5
reffering to this ui element
![image](https://github.com/Shirk/statustimers/assets/86545774/e751490c-f627-4b5c-b486-a14d52eff865)

**Comment by Shirk** [comment]
v4.1.501 reverts to the old method of hiding the native icons.
That code also has some issues (it causes the game to constantly try to reload the icon resources) but apparently people care more for keyboard cancelling than added CPU usage.
