### ISSUE TITLE
Timers appear with thousands of hours extra duration than they should have.

### ISSUE THREAD

**Issue by Schiferl** [Shirk/statustimers#12]
![image](https://github.com/Shirk/statustimers/assets/4484720/412aa4f4-bfbb-479d-83ef-e1fb008abf70)

I have reloaded the addon, restarted the game, and redownloaded the addon. Nothing seems to fix it. Other people I have asked so far are not having the issue.

**Comment by Shirk** [comment]
Which version are you using and are you playing on retail or a private server?

(also, are you by chance using the timers addon as it's known to have messed up statustimers in the past)

**Comment by Schiferl** [comment]
Private server (HorizonXI). Not using Timers, never have.

**Comment by Schiferl** [comment]
Worth noting that the correct timers are actually showing in the top left corner. I don't think those are supposed to show while StatusTimers is on?

![image](https://github.com/Shirk/statustimers/assets/4484720/837de4b4-8dd6-461a-a0d7-9577ba52f040)

**Comment by Schiferl** [comment]
I just redownloaded, so should be the most recent version: 
![image](https://github.com/Shirk/statustimers/assets/4484720/c532d6b4-006c-4f13-9d70-1c2cbe9f9d45)

**Comment by Schiferl** [comment]
Deleted the statustimers config files. Rebooted my computer. Still broken :(

Checked my mule characters and It happens for them too.

**Comment by Shirk** [comment]
Looks like the game's internal timestamp has overflowed yet again - I'll add a fix soon.
No clue why the native UI blocking doesn't work for you either but there's a change I want to roll back in that regard as well.

**Comment by Sulryn** [comment]
I'm having the same issue on retail. Also I noticed that the addon currently blcoks the native UI icons but not the timer. I remember in past version the native timer blocking is kind of wonky and the native timer would sometimes start flickering on and off.

**Comment by Shirk** [comment]
> I'm having the same issue on retail. Also I noticed that the addon currently blcoks the native UI icons but not the timer. I remember in past version the native timer blocking is kind of wonky and the native timer would sometimes start flickering on and off.

The native timers display (not the icons) has always been a game option that you can turn off from XI's native config menu. 

Also, yes, the issue happens on retail and any other version of the game right now because they all use the same vanatime timestamp. As I already said, it'll be addressed in a new version once I have time.

**Comment by Shirk** [comment]
Addressed in Release v4.1.501
