### ISSUE TITLE
Dedication Status Displayed as Refresh

### ISSUE THREAD

**Issue by flanagak** [Shirk/statustimers#2]
Using Icon Set 2.

Dedication buff from Kupofried, Echad Ring, Trizek Ring...(ect)
All are showing the Refresh (MP) icon instead of the EXP icon.

Last one in picture is Dedication from Kupofried.
![image](https://user-images.githubusercontent.com/23747969/170084805-67b97084-cc0f-4c29-962c-27806e9e0fb3.png)

**Comment by Shirk** [comment]
Nothing I can do there, I simply display the icon the game associates with the status ID the server tells it. 
Are you on retail?

**Comment by flanagak** [comment]
Yes I am on retail.
Yes the settings UI -> Filter shows the icon as Refresh(MP) as well.

**Comment by flanagak** [comment]
Buff ID is #249

**Comment by flanagak** [comment]
On another note....

Would it be possible to add a "padding" setting or some way to add some separation between the status icons?
