### ISSUE TITLE
Does not load name of 6th party member, v4.0.910

### ISSUE THREAD

**Issue by Chibloom** [Shirk/statustimers#6]
for specialkid focus
![image](https://user-images.githubusercontent.com/86545774/218287501-2022ec03-80ea-4da0-8cd3-5b7666d82a17.png)
![image](https://user-images.githubusercontent.com/86545774/218287623-10975b44-8122-448e-a3dd-0c97d9d20963.png)

meanwhile when trying to focus zappa
![image](https://user-images.githubusercontent.com/86545774/218287663-bbe22eae-18ee-43d3-81d2-ea670cd57b23.png)
![image](https://user-images.githubusercontent.com/86545774/218287700-32d6b8eb-681c-4354-b9e2-2abbdd788e97.png)

it is refusing to grab the name for the 6th party member, unless list is rearranged for it to not be 6th on the list

Playing on Horizion private server
also cannot lock for 6th party member's status

**Comment by Chibloom** [comment]
soryr it looks like paint cropped out the images, will reupload in a bit

**Comment by Chibloom** [comment]
Can make it lock by setting the member to be not 6th, but the name will disappear upon putting them on 6th. Statuses will remain locked tho

**Comment by Shirk** [comment]
Thanks for catching this one - classic off-by-one in lua loops ^^'

Should be working fine in the [lastest release](https://github.com/Shirk/statustimers/releases/tag/v4.0.911)
