### ISSUE TITLE
Might have left a debug print

### ISSUE THREAD

**Issue by GetAwayCoxn** [Shirk/statustimers#7]
Or perhaps its intentional? Figured was a debug print left over.

line 258 in party.lua to save you some look up time
first time trying this addon out, pretty neat!

![picforheals](https://user-images.githubusercontent.com/66495755/222903722-b0f7cfdd-a067-4b43-af36-a72f879fa201.png)

**Comment by Shirk** [comment]
Oh yeah, that one was a left over when I redid the signature scans. I'll remove it with the next update!

**Comment by GetAwayCoxn** [comment]
no worries! my first time checking this addon out, great work!
